### ISSUE TITLE
IPv6 support is broken

### ISSUE THREAD

**Issue by tjankow** [ARMmbed/mbed-client-linux#19]
I was unable to run mbed-client-linux-examples with IPv6 LWM2M server. Server's address was translated into garbage (checked with Wireshark).
```
_interface = M2MInterfaceFactory::create_interface(*this,
                                                  "coap://fd00:ff1:ce0b:a5e0::1:5683",
                                                  "test",
                                                  3600,
                                                  port,
                                                  "",
                                                  M2MInterface::UDP,
                                                  M2MInterface::LwIP_IPv6,
```
 I investigated mbed-client-linux and found two bugs causing, at least partially, this problem:

* `_sa_dst` and  `_sa_src` are `sockaddr_in` - that makes them IPv4 only; file m2mconnectionhandlerpimpl.h, line 139
* code at line 167 in file m2mconnectionhandlerpimpl.cpp blindly treats server address structure as IPv4  irrespective of what was previously done (lines 97-164)

**Comment by yogpan01** [comment]
Thanks for reporting ! We will look into this.

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTCLT-391

**Comment by anttiylitokola** [comment]
Hi, IPv6 support is now added in mbed-client-linux version 1.1.3.
