### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by BlackstoneEngineering** [ARMmbed/mbed-client-linux#23]
Please modify the readme so it is clear this this is a yotta module and point to the example code that uses this mode  : https://github.com/ARMmbed/mbed-client-linux-example.git

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-545

**Comment by kuggenhoffen** [comment]
I've added a description that this is a yotta module as well as a link to the mbed-client-linux-example repository for reference on how this is used.
