### ISSUE TITLE
initialization socket twice

### ISSUE THREAD

**Issue by BenGant** [ARMmbed/mbed-client-linux#30]
It seems that you initializate socket twice:
In functionM2MConnectionHandlerPimpl::resolve_server_address:

_socket_server=socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP);
                    if(_binding_mode == M2MInterface::TCP ||
                       _binding_mode == M2MInterface::TCP_QUEUE ){
                        _socket_server=socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
                    }else{
                        _socket_server=socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP);
                    }

**Comment by yogpan01** [comment]
Hi, thanks for reporting. This is now fixed and released. Please do "yotta update" to get the latest fixed sources.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-608
