### ISSUE TITLE
How to run unit tests

### ISSUE THREAD

**Issue by vanti** [ARMmbed/mbed-client-linux#45]
Hi,

I do not see any documentation that explains how to build and run the unit tests in this module under Linux. I tried to build the module and its tests using 'yotta build', but it results in build errors such as follows:

> 
> /home/workdir/yottaenv/mbed-client-linux/test/mbed-client-linux/unittest/m2mconnectionhandlerimpl_linux/m2mconnectionhandlerimpl_linuxtest.cpp:17:34: fatal error: CppUTest/TestHarness.h: No such file or directory
>  #include "CppUTest/TestHarness.h"
> 
> /home/workdir/yottaenv/mbed-client-linux/test/mbed-client-linux/unittest/m2mconnectionhandlerimpl_linux/main.cpp:16:44: fatal error: CppUTest/CommandLineTestRunner.h: No such file or directory
>  #include "CppUTest/CommandLineTestRunner.h"

I do not see these header files being provided in the repository. Any advice?
Thanks in advance.

**Comment by kuggenhoffen** [comment]
Hi, 
you will need to install some additional dependencies (cpputest, lcov, xsltproc and gcovr) to run unittests. If you are using Ubuntu/Debian you can do:
`sudo apt-get install cpputest lcov xsltproc`
and 
`pip install gcovr`

After those dependencies are installed you should be able to run unittests with `make test`.

Thanks for reporting this, I'll add some instructions to the readme as well.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-831

**Comment by kuggenhoffen** [comment]
I've added the instructions to the readme as well now.
