### ISSUE TITLE
Making start() and stop_timer() in M2MTimerPimpl more efficient

### ISSUE THREAD

**Issue by vanti** [ARMmbed/mbed-client-linux#50]
A suggestion to make the implementation more efficient is to call timer_create()/timer_delete() in the M2MTimerPimpl constructor and destructor, and simply use timer_settime() to arm/disarm the timer. In this manner we don't have to create a brand new posix timer every time we wish to start/stop the M2MTimer. See attached for what I have in mind. 

[m2mtimerpimpl.zip](https://github.com/ARMmbed/mbed-client-linux/files/344217/m2mtimerpimpl.zip)

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-849

**Comment by yogpan01** [comment]
Thanks for the proposal. We will check and try to update the implementation accordingly.

**Comment by yogpan01** [comment]
Released
