### ISSUE TITLE
mbedtls context needs protection when accessed from multiple threads

### ISSUE THREAD

**Issue by vanti** [ARMmbed/mbed-client-linux#52]
In light of this discussion: https://github.com/ARMmbed/mbedtls/issues/564, the mbedtls context needs to be protected when accessed via multiple threads. Multi-thread accesses are performed in mbed-client-linux. For instance, the data listener thread calls M2MConnectionHandlerPimpl::data_receive() in the background. Application threads might be calling M2MConnectionHandlerPimpl::send_data() concurrently and access the same mbedtls context, leading to potential race conditions.

**Comment by vanti** [comment]
Any update on this issue?

**Comment by yogpan01** [comment]
Hi,
We do have protection mechanism for simultaneous calls, however, mutex locks have been missing in Linux implementation. We will try to fix this soon.

**Comment by kuggenhoffen** [comment]
Hi,
The mbedtls calls from M2MConnectionHandlerPimpl are now serialized using an eventloop and thus protected from race conditions in mbed-client-linux version 3.1.0.
